### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Ulbrec87** [SetBased/php-audit#14]
Could you write some documentation/example ? 
Thanks !

**Comment by prwater** [comment]
Hello Ulbrec87,

Thank you very much for your interest in out project.

I will write a README for this project tomorrow. Are you looking for some specific functionalities.

With best regards,
Paul

**Comment by prwater** [comment]
Please, review the documentation at Read the Docs: https://php-audit.readthedocs.io/en/latest/?badge=latest
