### ISSUE TITLE
Database credentials should be separated from config.json files

### ISSUE THREAD

**Issue by olleharstedt** [SetBased/php-audit#63]
Config files in JSON format will probably be pushed to a repository, but database credentials should of course not. Therefore, there should be a separate config file for the database user and password, etc, that can be added to .gitignore.

**Comment by prwater** [comment]
In the ```database ``` section has an optional key ```credentials```. This configuration setting is filename (relative to the ```audit.json```) with ```database``` settings that will override the ```database``` settings in ```audit.json```. 

You can choose to store only the password in the credentials file or all database settings.

You can choose your favorite configuration format for the credentials file: ini, json, xml, or yml.

Same examples can be found at:
* https://github.com/SetBased/php-audit/tree/master/test/MySql/AuditCommand/AbcFramework/config
* https://github.com/SetBased/php-audit/tree/master/test/MySql/AuditCommand/AddColumn/config
